// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionBar.Data;

#nullable disable

namespace SistemaGestionBar.Data.Migraciones
{
    [DbContext(typeof(BarDbContext))]
    [Migration("20260914180334_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestionBar.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre_categoria");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdCategoria");

                    b.HasIndex("NombreCategoria")
                        .IsUnique();

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<string>("CajeroNombre")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("cajero_nombre");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("cliente_nombre");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("importe");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdVenta")
                        .IsUnique();

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("factura", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.FacturaLinea", b =>
                {
                    b.Property<int>("IdFacturaLinea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_factura_linea");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFacturaLinea"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdFacturaLinea");

                    b.HasIndex("IdFactura");

                    b.ToTable("factura_linea", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Ingrediente", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ingrediente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdIngrediente"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("stock");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("stock_minimo");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("unidad_medida");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdIngrediente");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ingrediente", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_metodo_pago");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("NombreMetodo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre_metodo");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdMetodoPago");

                    b.HasIndex("NombreMetodo")
                        .IsUnique();

                    b.ToTable("metodo_pago", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("apellido");

                    b.Property<string>("DniCuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni_cuit");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdPersona");

                    b.HasIndex("DniCuit")
                        .IsUnique();

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio");

                    b.Property<string>("RutaImagen")
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)")
                        .HasColumnName("ruta_imagen");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int")
                        .HasColumnName("stock_minimo");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.ProductoIngrediente", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("int")
                        .HasColumnName("id_ingrediente");

                    b.Property<decimal>("CantidadNecesaria")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("cantidad_necesaria");

                    b.HasKey("IdProducto", "IdIngrediente");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("producto_ingrediente", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Receta", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("preparacion");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdProducto");

                    b.ToTable("receta", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre_rol");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Ubicacion", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUbicacion"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int")
                        .HasColumnName("capacidad");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("NombreUbicacion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre_ubicacion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_ubicacion");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdUbicacion");

                    b.HasIndex("NombreUbicacion")
                        .IsUnique();

                    b.ToTable("ubicacion", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("clave");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<string>("EstadoVenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado_venta");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_hora");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdCajero")
                        .HasColumnType("int")
                        .HasColumnName("id_cajero");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdMesero")
                        .HasColumnType("int")
                        .HasColumnName("id_mesero");

                    b.Property<int>("IdMetodoPago")
                        .HasColumnType("int")
                        .HasColumnName("id_metodo_pago");

                    b.Property<int?>("IdUbicacion")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    b.Property<string>("ModalidadConsumo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("modalidad_consumo");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdCajero");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMesero");

                    b.HasIndex("IdMetodoPago");

                    b.HasIndex("IdUbicacion");

                    b.ToTable("venta", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.VentaDetalle", b =>
                {
                    b.Property<int>("IdVentaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_venta_detalle");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVentaDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdVentaDetalle");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("venta_detalle", (string)null);
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Cliente", b =>
                {
                    b.HasOne("SistemaGestionBar.Models.Persona", "Persona")
                        .WithOne("Cliente")
                        .HasForeignKey("SistemaGestionBar.Models.Cliente", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Factura", b =>
                {
                    b.HasOne("SistemaGestionBar.Models.Venta", "Venta")
                        .WithOne()
                        .HasForeignKey("SistemaGestionBar.Models.Factura", "IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.FacturaLinea", b =>
                {
                    b.HasOne("SistemaGestionBar.Models.Factura", null)
                        .WithMany("Lineas")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Producto", b =>
                {
                    b.HasOne("SistemaGestionBar.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.ProductoIngrediente", b =>
                {
                    b.HasOne("SistemaGestionBar.Models.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionBar.Models.Producto", "Producto")
                        .WithMany("Ingredientes")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Receta", b =>
                {
                    b.HasOne("SistemaGestionBar.Models.Producto", "Producto")
                        .WithOne("Receta")
                        .HasForeignKey("SistemaGestionBar.Models.Receta", "IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Usuario", b =>
                {
                    b.HasOne("SistemaGestionBar.Models.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("SistemaGestionBar.Models.Usuario", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionBar.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Venta", b =>
                {
                    b.HasOne("SistemaGestionBar.Models.Usuario", "Cajero")
                        .WithMany()
                        .HasForeignKey("IdCajero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionBar.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionBar.Models.Usuario", "Mesero")
                        .WithMany()
                        .HasForeignKey("IdMesero")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaGestionBar.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionBar.Models.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("IdUbicacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cajero");

                    b.Navigation("Cliente");

                    b.Navigation("Mesero");

                    b.Navigation("MetodoPago");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.VentaDetalle", b =>
                {
                    b.HasOne("SistemaGestionBar.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionBar.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Factura", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Persona", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Producto", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaGestionBar.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
